name: Check Pages Status

on: page_build

permissions:
  contents: read

jobs:
  pages-status-check:
    runs-on: ubuntu-22.04
    steps:
      - name: check status
        env:
          BUILD_STATUS: ${{ github.event.build.status }}
          BUILD_ERROR_MESSAGE: ${{ github.event.build.error.message }}
        run: |
          import os
          status = os.environ['BUILD_STATUS']
          errormsg = os.environ['BUILD_ERROR_MESSAGE']
          assert status == 'built', 'Status: {status}\nError: {errormsg}'.format(status=status, errormsg=errormsg)
        shell: python
